name: Vérification EVC

on:
  schedule:
    - cron: '*/5 * * * *'  # Exécuter chaque minute
  workflow_dispatch:  # Permet de lancer manuellement

jobs:
  check_update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Installer les dépendances
        run: pip install requests beautifulsoup4
      - name: Exécuter le script
        run: python script.py
